export interface Referee {
  id: string;
  name: string;
}

export const REFEREES: Referee[] = [
  { id: 'ref-1', name: 'Adins Shane' },
  { id: 'ref-2', name: 'Bas Wietse' },
  { id: 'ref-3', name: 'Beyens Timo' },
  { id: 'ref-4', name: 'Bieseman Helena' },
  { id: 'ref-5', name: 'Blommaert Joren' },
  { id: 'ref-6', name: 'Blommaert Marc' },
  { id: 'ref-7', name: 'Bogaert Maarten' },
  { id: 'ref-8', name: 'Bonne Curt' },
  { id: 'ref-9', name: 'Borra Julie' },
  { id: 'ref-10', name: 'Bosman Dirk' },
  { id: 'ref-11', name: 'Braem Walter' },
  { id: 'ref-12', name: 'Bruckner Louis' },
  { id: 'ref-13', name: 'Calleeuw Kristof' },
  { id: 'ref-14', name: 'Catry Senne' },
  { id: 'ref-15', name: 'Claes Pol' },
  { id: 'ref-16', name: 'Claeys Koen' },
  { id: 'ref-17', name: 'Claeys Maarten' },
  { id: 'ref-18', name: 'Cool Kelly' },
  { id: 'ref-19', name: 'Cox Jos' },
  { id: 'ref-20', name: "D'hoore Marc" },
  { id: 'ref-21', name: 'De Love Sandra' },
  { id: 'ref-22', name: 'De Smet Jasper' },
  { id: 'ref-23', name: 'De Visscher Nette' },
  { id: 'ref-24', name: 'De Visscher Sam' },
  { id: 'ref-25', name: 'Deleu Lars' },
  { id: 'ref-26', name: 'Deleye Karel' },
  { id: 'ref-27', name: 'Demeulemeester Oskar' },
  { id: 'ref-28', name: 'Demeulenaere Luc' },
  { id: 'ref-29', name: 'Demunter Marc' },
  { id: 'ref-30', name: 'Devoldere Arwen' },
  { id: 'ref-31', name: 'Dhaese Anja' },
  { id: 'ref-32', name: 'Dhaese Antoon' },
  { id: 'ref-33', name: 'Emanuel Geert' },
  { id: 'ref-34', name: 'Flameyn Bjorn' },
  { id: 'ref-35', name: 'Flameyn Julie' },
  { id: 'ref-36', name: 'Gerlo Jonathan' },
  { id: 'ref-37', name: 'Gheselle Sander' },
  { id: 'ref-38', name: 'Goedgezelschap Sara' },
  { id: 'ref-39', name: 'Gorssen Theo' },
  { id: 'ref-40', name: 'Kerkaert Geert' },
  { id: 'ref-41', name: 'Kindermans Lander' },
  { id: 'ref-42', name: 'Knaepen Yenna' },
  { id: 'ref-43', name: 'Maenhout Eric' },
  { id: 'ref-44', name: 'Maes Matthias' },
  { id: 'ref-45', name: 'Marchand Filip' },
  { id: 'ref-46', name: 'Meersman Bert' },
  { id: 'ref-47', name: 'Mertens Wout' },
  { id: 'ref-48', name: 'Moens Kyrthe' },
  { id: 'ref-49', name: 'Mouton Finn' },
  { id: 'ref-50', name: 'Neckebroeck Bart' },
  { id: 'ref-51', name: 'Nieuwborg Rob' },
  { id: 'ref-52', name: 'Oosterlinck Peter' },
  { id: 'ref-53', name: 'Quintijn Stefaan' },
  { id: 'ref-54', name: 'Reumers Joris' },
  { id: 'ref-55', name: 'Reybrouck Erik' },
  { id: 'ref-56', name: 'Roggeman Bart' },
  { id: 'ref-57', name: 'Roze Eddy' },
  { id: 'ref-58', name: 'Soulliaert Henk' },
  { id: 'ref-59', name: 'Stassijns Jean-Pierre' },
  { id: 'ref-60', name: 'Stevens Stefan' },
  { id: 'ref-61', name: 'Steyaert Piet' },
  { id: 'ref-62', name: 'Strobbe Luc' },
  { id: 'ref-63', name: 'Timmerman Dirk' },
  { id: 'ref-64', name: 'Timmerman Kurt' },
  { id: 'ref-65', name: 'Vackier Tristan' },
  { id: 'ref-66', name: 'Van Belle Maaike' },
  { id: 'ref-67', name: 'Van Bosstraeten Charlot' },
  { id: 'ref-68', name: 'Van Den Berghe Tibo' },
  { id: 'ref-69', name: 'Van Deynse Andre' },
  { id: 'ref-70', name: 'Van Lierde Milan' },
  { id: 'ref-71', name: 'Van Nieuwkerke Stefaan' },
  { id: 'ref-72', name: 'Van Oudenhove Ignace' },
  { id: 'ref-73', name: 'Van Torre Louis' },
  { id: 'ref-74', name: 'Van Verre Willy' },
  { id: 'ref-75', name: 'Van den Berghe Ronald' },
  { id: 'ref-76', name: 'Vandenberghe Thomas' },
  { id: 'ref-77', name: 'Vandepoele Kurt' },
  { id: 'ref-78', name: 'Vander Stichele Robbe' },
  { id: 'ref-79', name: 'Vanhecke Jan' },
  { id: 'ref-80', name: 'Vanhoutte Wim' },
  { id: 'ref-81', name: 'Vanneste Andreas' },
  { id: 'ref-82', name: 'Wuyts Eric' }
];

export function getRefereeById(id: string): Referee | undefined {
  return REFEREES.find(referee => referee.id === id);
}

export function getRandomReferee(): Referee {
  const randomIndex = Math.floor(Math.random() * REFEREES.length);
  return REFEREES[randomIndex];
}
